### PR TITLE
The dependencies are updated to the latest requiremernts

### PR DESCRIPTION
**Pull request by mataspetrikas**
I have tried to get the latest puppeteer 1.7.0 to run on heroku with the previous buildpack version but it was complaining about the missing dependecies on start. I have replaced them with the ones from this source: https://github.com/GoogleChrome/puppeteer/issues/1627

It seems to be working well now with heroku.

### CODE REVIEW

**Comment by jontewks** [comment]
I mentioned an updated dependency list in the issue you created as well, please give that a shot and see if you can update this PR so we don't include a bunch of dependencies that docker needs but not heroku. I'd also love to get this fixed asap if people are going to start having issues with it

**Comment by jontewks** [comment]
Hey @mataspetrikas, I was hoping to wait for your changes so you could merge your PR, but if the buildpack was failing I really didn't want to wait around too long and cause many other people problems, so I updated the dependencies list with what Google says is needed for Puppeteer. Maybe you could try again with the most recent version of the buildpack and let me know if its fixed? If not we can continue from there and find out whats going on with your instance.

**Comment by joey2031** [comment]
I have the same issue and have no idea how to fix it. I was looking online and I added the buildpack needed using: heroku buildpacks:add --index 1 jontewks/puppeteer but im still getting the same error as shown in the image below. How can I fix this?
image

**Comment by jontewks** [comment]
@joey2031 can you post your heroku buildpack list, which heroku stack you are using, and package.json contents so we can take a look?

**Comment by joey2031** [comment]
Package.json: 
{
    "name": "twitterbot",
    "engines": {
        "node": "8.2.1"
    },
    "version": "1.0.0",
    "description": "",
    "main": "bot.js",
    "scripts": {
        "start": "node bot.js",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC",
    "dependencies": {
        "inspirational-quotes": "^1.0.8",
        "puppeteer": "^1.20.0",
        "quotes-photos-generator": "^1.0.5",
        "twit": "^2.2.11"
    }
}
The heroku buildpack list and heroku stack I am using is in the image below. Thanks!

image

**Comment by jontewks** [comment]
Thanks for that extra info. Everything there looks good. Its an exact match for this issue: https://github.com/jontewks/puppeteer-heroku-buildpack/issues/14 so that might be a good place to start. That person was able to resolve the issue by clearing their build cache, instructions here: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Give that a shot and let me know what happens.

**Comment by joey2031** [comment]
First I tried these commands

heroku plugins:install heroku-repo
$ heroku repo:purge_cache -a appname
$ git commit --allow-empty -m "Purge cache"
$ git push heroku master

and got the same result
Then I tried this

$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:purge_cache -a appname

and it still did not work.
Ive included screenshots and a link to the repo with the app im working on,
thanks for all of your help!
Github repo: https://github.com/joey2031/Twitter-Bot-Quotes

**Comment by jontewks** [comment]
Thanks for trying. My next best guesses would be to start upgrading some things and see if we can resolve it. I noticed the version of puppeteer you are using requests at least node 8.9.0+ but you're using 8.2.1. I doubt thats the issue but I've been surprised before. Maybe worth upgrading your node version, at least to the latest LTS version.

Also I'd try clicking the upgrade stack button from your screenshot to get heroku-18, as they all have separate dependencies that might help resolve the issue.

**Comment by joey2031** [comment]
Hi so I tried some things and here are some updates.
1. I checked and the version of node im running is 12.13.0
[image: image.png]
2. I changed the node version in package.json
3. I took out the engines part of package.json (updated version is on
github)- To be honest I don't know what's the point of that I just
found someone do it online and added it.
After all this, I'm still getting the same error.
I know this sounds crazy but you seem like a good guy and I trust you: is
it possible that you can fork the repo off of git hub, (ill send you bot.js
with the twitter keys). From there can you try to upload it to Heroku and
see if it works? Mabey i'm doing something wrong/ a silly mistake. (Sorry
to bother you im very new at this) Thank you so much for all of your help
and have a good day!

**Comment by jontewks** [comment]
Launching chrome usually isn't related to the content of the file, but its possible. Can you try it with just the following as the entire contents of the bot.js file?

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ args: ['--no-sandbox'] })
  const page = await browser.newPage()
  await page.goto('https://www.buildingconnected.com')

  console.log('WORKING')

  await browser.close()
  process.exit(0)
})()
```

**Comment by joey2031** [comment]
So I just tried it. When I run it locally I see the WORKING in the console
[image: output.JPG]
When I run upload it to heroku and run heroku logs --tail I no longer see
the "cannot open shared object file error" (error.jpg) however it still
says failed to launch chrome (error2.jpg) .
  error.jpg:
[image: error.JPG]
error2.jpg:
[image: error2.JPG]
Thank you so much for all your help.

**Comment by jontewks** [comment]
@joey2031 maybe try creating a new heroku app on heroku-18 and deploying fresh? With the above code I'm able to get it working right away. It must be some weird cache issue or something along those lines, as that was the cause of that other person running into the same error and since the same code is working elsewhere. LMK if you are able to try that out.

**Comment by joey2031** [comment]
The build succeeds however I don't see the console.log, ps. The new app is
a web app, not a worker- I think thats why. On the bright side im no longer
getting those errors about Chrome
[image: image.png]
[image: image.png]
I used these commands before deploying:

$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:purge_cache -a appname

**Comment by jontewks** [comment]
Cool. The console log will show up in the application logs which you can see in heroku's UI, and web vs worker shouldn't change dependencies available to either dyno type but if you are curious you could always swap it from web back to worker to verify. We have our puppeteer running on worker dynos so they aren't subject to the 30 second timeout that web dynos are. Either way glad its working now!

**Comment by joey2031** [comment]
So what should I do now? Just copy and paste bot.js, package.json and run
npm install.
Oh and btw thank you so much. Sorry for bugging you so much

**Comment by jontewks** [comment]
@joey2031 yeah that should be it and no problem at all. Good luck!

**Pull request closed without merging**
